module.exports.realBothies = [
    {
        title: 'Achnanclach',
        district: 'Sutherland',
        region: 'Northern Highlands',
        description: 'N/A',
        lat: 58.427,
        lon: -4.346,
    },
    {
        title: `Coiremor, Magoo's Bothy`,
        district: 'Ross-shire',
        region: 'Northern Highlands',
        description: 'Quite a large bothy. No fuel.',
        lat: 57.857,
        lon: -4.858,	
    },
    {
        title: 'Croft House, Lochstrathy',
        district: 'Sutherland',
        region: 'Northern Highlands',
        description: 'This bothy feels about a million miles from anywhere. Spacious with plenty of nearby firewood.',
        lat: 58.412,
        lon: -4.067,
    },
    {
        title: 'Glencoul',
        district: 'Sutherland',
        region: 'Northern Highlands',
        description: 'Charming bothy in a great location. Limited driftwood fuel nearby.',
        lat: 58.228,
        lon: -4.947,
    },
    {
        title: 'Glendhu',
        district: 'Sutherland',
        region: 'Northern Highlands',
        description: 'Charming bothy in a beautiful landscape. Limited driftwood nearby.',
        lat: 58.259,
        lon: -4.928,
    },
    {
        title: 'Kearvaig',
        district: 'Sutherland',
        region: 'Northern Highlands',
        description: 'Large and handsome bothy. Access is sometimes restricted by bombing range exercises. Check when planning your trip!',
        lat: 58.609,
        lon: -4.941,
    },
    {
        title: 'Knockdamph',
        district: 'Sutherland',
        region: 'Northern Highlands',
        description: 'Large bothy with lots of sleeping space. No firewood nearby.',
        lat: 57.915,
        lon: -4.895,
    },
    {
        title: 'Schoolhouse, Duag Bridge',
        district: 'Sutherland',
        region: 'Northern Highlands',
        description: 'Small bothy with two rooms in an old schoolhouse. No fire or stove.',
        lat: 57.935,
        lon: -4.805,
    },
    {
        title: 'Shenavall',
        district: 'Wester Ross',
        region: 'Northern Highlands',
        description: 'Large and very heavily used bothy.',
        lat: 57.777,
        lon: -5.254,
    },
    {
        title: 'Strabeg',
        district: 'Sutherland',
        region: 'Northern Highlands',
        description: 'Large bothy with some unexpected luxury...',
        lat: 58.425,
        lon: -4.756,
    },
    {
        title: 'Strathan',
        district: 'Sutherland',
        region: 'Northern Highlands',
        description: 'Basic bothy. Possible peat fuel nearby.',
        lat: 58.503,
        lon: -5.010,
    },
    {
        title: 'Strathchailleach',
        district: 'Sutherland',
        region: 'Northern Highlands',
        description: 'Smallish bothy with peat fuel nearby. Used as a house for a while by a man named Sandy who painted the interior walls with pointillist murals.',
        lat: 58.545,
        lon: -5.010,
    },
    {
        title: 'Suileag',
        district: 'Sutherland',
        region: 'Northern Highlands',
        description: 'N/A',
        lat: 58.140,
        lon: -5.145,
    },
    {
        title: 'Bearnais',
        district: 'Wester Ross',
        region: 'North West Highlands and Islands',
        description: 'Small bothy up in the hills. Can be tricky to find in the dark or mist. No fuel nearby.',
        lat: 57.434,
        lon: -5.298,
    },
    {
        title: 'Camasunary',
        district: 'Skye',
        region: 'North West Highlands and Islands',
        description: 'A new bothy.',
        lat: 57.190,
        lon: -6.112,
    },
    {
        title: 'Camban',
        district: 'Kintail',
        region: 'North West Highlands and Islands',
        description: 'Utilitarian bothy on popular walking route. Lots of sleeping platforms. Reputedly supports a population of hamsters.',
        lat: 57.214,
        lon: -5.225,
    },
    {
        title: 'Coire Fionnaraich',
        district: 'Wester Ross',
        region: 'North West Highlands and Islands',
        description: 'Large and well-used bothy. no fuel.',
        lat: 57.476,
        lon: -5.421,
    },
    {
        title: 'Craig',
        district: 'Wester Ross',
        region: 'North West Highlands and Islands',
        description: 'A large ex youth hostel. Many rooms, large stove, flushing loo! Driftwood on beach.',
        lat: 57.610,
        lon: -5.727,
    },
    {
        title: 'Easan Dorcha (The Teahouse)',
        district: 'Wester Ross',
        region: 'North West Highlands and Islands',
        description: `Not really a place to plan to stay overnight. More of a nice shed for eating your sandwiches when it's raining.`,
        lat: 57.519,
        lon: -5.323,
    },
    {
        title: 'Lookout (Rubha Hunish)',
        district: 'Skye',
        region: 'North West Highlands and Islands',
        description: `Small bothy in coastguard lookout station on Rubha Hunish on Skye. Sleeping space for a couple of people only. No fresh water apart from rainwater collection tank from roof. Great spot for dolphin and whale watching.`,
        lat: 57.701,
        lon: -6.344,
    },
    {
        title: 'Maol Bhuidhe',
        district: 'Wester Ross',
        region: 'North West Highlands and Islands',
        description: `Medium sized bothy well off the beaten track. Several sleeping areas. No fuel.`,
        lat: 57.372,
        lon: -5.241,
    },
    {
        title: 'Ollisdal',
        district: 'Skye',
        region: 'North West Highlands and Islands',
        description: `Small bothy with two rooms. One furnished with fire and one unfurnished with dirt floor. Driftwood available for fuel nearby.`,
        lat: 57.360,
        lon: -6.636,
    },
    {
        title: 'Taigh Thormoid Dhuibh (Raasay)',
        district: 'Skye',
        region: 'North West Highlands and Islands',
        description: 'Secluded bothy on Raasay surrounded by ruined crofts. Can be surprisingly difficult to find!',
        lat: 57.499,
        lon: -5.988,
    },
    {
        title: 'Uags',
        district: 'Applecross',
        region: 'North West Highlands and Islands',
        description: 'Charming bothy in picturesque location overlooking Skye. Some driftwood nearby, plenty of sleeping space.',
        lat: 57.349,
        lon: -5.787,
    },
    {
        title: 'Uisinis',
        district: 'Outer Hebrides',
        region: 'North West Highlands and Islands',
        description: 'N/A',
        lat: 57.280,
        lon: -7.231,
    },
    {
        title: `A' Chuil`,
        district: 'Lochaber',
        region: 'Western Highlands',
        description: 'Medium sized bothy. Couple of rooms with sleeping space.',
        lat: 56.977,
        lon: -5.384,
    },
    {
        title: 'Dibidil',
        district: 'Rùm',
        region: 'Western Highlands',
        description: 'Medium sized bothy with a couple of rooms and sleeping platforms.',
        lat: 56.952,
        lon: -6.289,
    },
    {
        title: 'Gleann Dubh-lighe',
        district: 'Lochaber',
        region: 'Western Highlands',
        description: 'N/A',
        lat: 56.884,
        lon: -5.375,
    },
    {
        title: 'Glenpean',
        district: 'Lochaber',
        region: 'Western Highlands',
        description: 'Large bothy, stove. Firewood nearby.',
        lat: 56.958,
        lon: -5.396,
    },
    {
        title: 'Guirdil',
        district: 'Rùm',
        region: 'Western Highlands',
        description: 'Spacious bothy with mezzanine sleeping area. Fireplace. Driftwood and kelp on beach for fuel (and elusive bloodstones)',
        lat: 57.025,
        lon: -6.418,
    },
    {
        title: 'Invermallie',
        district: 'Lochaber',
        region: 'Western Highlands',
        description: 'Large bothy but prone to flooding. Likely to find some firewood nearby.',
        lat: 56.953,
        lon: -5.067,
    },
    {
        title: 'Kinbreack',
        district: 'Lochaber',
        region: 'Western Highlands',
        description: 'Fairly large building but only the upstairs is furnished for sleeping.',
        lat: 57.013,
        lon: -5.292,
    },
    {
        title: 'Oban',
        district: 'Lochaber',
        region: 'Western Highlands',
        description: 'N/A',
        lat: 56.952,
        lon: -5.515,
    },
    {
        title: 'Sourlies',
        district: 'Lochaber',
        region: 'Western Highlands',
        description: 'A well-known and popular bothy in the heart of Knoydart. Small and frequently very busy so be prepared to camp.',
        lat: 56.997,
        lon: -5.513,
    },
    {
        title: 'Suardalan',
        district: 'Lochaber',
        region: 'Western Highlands',
        description: 'Handy for cycle tourists heading to the manual turntable ferry at Glenelg on the way to Skye. Quite a large bothy, not heavily used.',
        lat: 57.197,
        lon: -5.506,
    },
    {
        title: 'Abyssinia',
        district: 'Loch Lomond',
        region: 'Southwest Highlands and Islands',
        description: 'A relatively new bothy!',
        lat: 56.266,
        lon: -4.818,
    },
    {
        title: 'Cadderlie',
        district: 'North Argyll',
        region: 'Southwest Highlands and Islands',
        description: 'Medium sized bothy with several rooms. Popular with anglers. Firewood nearby.',
        lat: 56.486,
        lon: -5.175,
    },
    {
        title: 'Carron',
        district: 'Knapdale',
        region: 'Southwest Highlands and Islands',
        description: 'One room bothy. Plenty of firewood nearby.',
        lat: 56.145,
        lon: -5.311,
    },
    {
        title: 'Cruib',
        district: 'Jura',
        region: 'Southwest Highlands and Islands',
        description: 'Recently restored and turned into a bothy by the MBA. Although a relatively short distance from the road, the terrain to get to this bothy is extremely hard going.',
        lat: 55.977,
        lon: -5.902,
    },
    {
        title: 'Doune Byre',
        district: 'Loch Lomond',
        region: 'Southwest Highlands and Islands',
        description: 'N/A',
        lat: 56.293,
        lon: -4.696,
    },
    {
        title: 'Essan',
        district: 'Wester Ross',
        region: 'Southwest Highlands and Islands',
        description: 'Not far from the main road but difficult to get to because of the loch. Common route is via the railway line although walking on the railway is technically trespassing.',
        lat: 56.875,
        lon: -5.584,
    },
    {
        title: 'Glengarrisdale',
        district: 'Jura',
        region: 'Southwest Highlands and Islands',
        description: 'Medium sized bothy. Although a short distance from the road it is difficult and hilly terrain. May be driftwood in the bay for the fire.',
        lat: 56.107,
        lon: -5.790,
    },
    {
        title: 'Leacraithnaich',
        district: 'Ardgour',
        region: 'Southwest Highlands and Islands',
        description: 'Medium sized bothy. Not very remote.',
        lat: 56.562,
        lon: -5.676,
    },
    {
        title: 'Mark Cottage',
        district: 'Loch Lomond',
        region: 'Southwest Highlands and Islands',
        description: 'N/A',
        lat: 56.116,
        lon: -4.849,
    },
    {
        title: 'Resourie',
        district: 'Ardgour',
        region: 'Southwest Highlands and Islands',
        description: 'Medium sized bothy has stove and plentiful firewood. It is very gloomy now that the commercial forestry has grown up around it.',
        lat: 56.781,
        lon: -5.502,
    },
    {
        title: 'Rowchoish',
        district: 'Loch Lomond',
        region: 'Southwest Highlands and Islands',
        description: 'N/A',
        lat: 56.202,
        lon: -4.684,
    },
    {
        title: `Taigh Seumas a' Ghlinne (Glen Duror)`,
        district: 'Lochaber',
        region: 'Southwest Highlands and Islands',
        description: 'One-room bothy in forest. Stove and plenty of firewood.',
        lat: 56.635,
        lon: -5.227,
    },
    {
        title: 'Tomsleibhe',
        district: 'Mull',
        region: 'Southwest Highlands and Islands',
        description: 'Large bothy with multiple rooms. Lots of midges.',
        lat: 56.466,
        lon: -5.869,
    },
    {
        title: 'Ben Alder Cottage',
        district: 'Rannoch',
        region: 'Central Highlands',
        description: 'Medium sized bothy',
        lat: 56.779,
        lon: -4.459,
    },
    {
        title: 'Blackburn of Corrieyairack',
        district: 'Monadhliath',
        region: 'Central Highlands',
        description: 'Medium sized bothy. No fuel nearby.',
        lat: 57.088,
        lon: -4.672,
    },
    {
        title: 'Culra',
        district: 'Monadhliath',
        region: 'Central Highlands',
        description: `Quite large bothy with several separate rooms. Unfortunately closed for the time being due to asbestos, latest update is that it will need to be completely rebuilt. Ben Alder cottage is nearby.`,
        lat: 56.854,
        lon: -4.424,
    },
    {
        title: 'Glenbuck',
        district: 'Monadhliath',
        region: 'Central Highlands',
        description: 'Large bothy with many rooms. Firewood nearby.',
        lat: 57.057,
        lon: -4.746,
    },
    {
        title: 'Gorton',
        district: 'Rannoch',
        region: 'Central Highlands',
        description: 'Large, lonely bothy. No firewood.',
        lat: 56.597,
        lon: -4.649,
    },
    {
        title: 'Lairig Leacach',
        district: 'Lochaber',
        region: 'Central Highlands',
        description: 'Small and basic bothy. Unsuitable for groups',
        lat: 56.823,
        lon: -4.816,
    },
    {
        title: 'Loch Chiarain',
        district: 'Lochaber',
        region: 'Central Highlands',
        description: 'Large bothy with lots of sleeping space. No firewood nearby.',
        lat: 56.731,
        lon: -4.798,
    },
    {
        title: 'Luib Chonnal',
        district: 'Monadhliath',
        region: 'Central Highlands',
        description: 'Large bothy. Upstairs renovated. Rivers in this area can be tricky to cross.',
        lat: 57.006,
        lon: -4.646,
    },
    {
        title: 'Meanach',
        district: 'Lochaber',
        region: 'Central Highlands',
        description: 'Medium sized bothy. Unlikely to have firewood nearby. Rivers can be difficult to cross in this area when in spate.',
        lat: 56.775,
        lon: -4.839,
    },
    {
        title: 'Staoineag',
        district: 'Lochaber',
        region: 'Central Highlands',
        description: 'Medium sized bothy. Unlikely to find firewood nearby.',
        lat: 56.771,
        lon: -4.791,
    },
    {
        title: 'Allt Scheicheachan',
        district: 'Badenoch',
        region: 'Eastern Highlands',
        description: 'Small busy cosy bothy. Only half furnished.',
        lat: 56.840,
        lon: -3.912,
    },
    {
        title: 'Callater Stable',
        district: 'Mounth',
        region: 'Eastern Highlands',
        description: 'Small and quite basic bothy. No fire or stove.',
        lat: 56.944,
        lon: -3.353,
    },
    {
        title: 'Charr',
        district: 'Mounth',
        region: 'Eastern Highlands',
        description: ' Medium sized bothy.',
        lat: 56.938,
        lon: -2.633,
    },
    {
        title: 'Corrour',
        district: 'Cairngorms',
        region: 'Eastern Highlands',
        description: 'Small and very heavily used bothy. Do not depend on being able to sleep in here as it could be very busy.',
        lat: 57.042,
        lon: -3.681,
    },
    {
        title: 'Faindouran',
        district: 'Cairngorms',
        region: 'Eastern Highlands',
        description: `Small bothy that doesn't seem much used. No fuel.`,
        lat: 57.137,
        lon: -3.519,
    },
    {
        title: 'Fords of Avon Refuge Hut',
        district: 'Cairngorms',
        region: 'Eastern Highlands',
        description: 'Small emergency refuge. Unsuitable for planned overnight stays.',
        lat: 57.110,
        lon: -3.584,
    },
    {
        title: 'Garbh Choire Refuge',
        district: 'Cairngorms',
        region: 'Eastern Highlands',
        description: 'Small emergency refuge. Unsuitable for planned overnight stays.',
        lat: 57.067,
        lon: -3.718,
    },
    {
        title: 'Gelder Shiel Stable',
        district: 'Mounth',
        region: 'Eastern Highlands',
        description: 'Quite a large bothy with lots of sleeping space. No fire or stove.',
        lat: 56.995,
        lon: -3.224,
    },
    {
        title: 'Glas Allt Shiel Bothy',
        district: 'Loch Muick',
        region: 'Eastern Highlands',
        description: 'N/A',
        lat: 56.927,
        lon: -3.191,
    },
    {
        title: 'Hutchinson Memorial Hut',
        district: 'Cairngorms',
        region: 'Eastern Highlands',
        description: 'Small hut, limited sleeping space. No stove etc.',
        lat: 57.078,
        lon: -3.613,
    },
    {
        title: 'Ruigh Aiteachain',
        district: 'Cairngorms',
        region: 'Eastern Highlands',
        description: 'Medium sized bothy in the beautiful remnant woodlands of Glen Feshie. There is usually some firewood stacked outside.',
        lat: 57.012,
        lon: -3.900,
    },
    {
        title: 'Ruighe Ealasaid (Red House)',
        district: 'Cairngorms',
        region: 'Eastern Highlands',
        description: 'N/A',
        lat: 56.962,
        lon: -3.643,
    },
    {
        title: 'Ryvoan',
        district: 'Cairngorms',
        region: 'Eastern Highlands',
        description: 'Medium sized bothy. Very easy to access from Glenmore so can be rather busy.',
        lat: 57.184,
        lon: -3.646,
    },
    {
        title: 'Shielin of Mark',
        district: 'Mounth',
        region: 'Eastern Highlands',
        description: 'Very small bothy with limited sleeping room. Small stove. Navigation is tricky in this area in dark and mist.',
        lat: 56.930,
        lon: -3.092,
    },
    {
        title: 'Tarf Hotel (Feith Uaine)',
        district: 'Badenoch',
        region: 'Eastern Highlands',
        description: 'Large bothy with lots and lots of room. No firewood.',
        lat: 56.889,
        lon: -3.763,
    },
    {
        title: 'Brattleburn',
        district: 'Lowther Hills',
        region: 'Southern Scotland',
        description: 'N/A',
        lat: 55.346,
        lon: -3.554,
    },
    {
        title: 'Burlywhag',
        district: 'Lowther Hills',
        region: 'Southern Scotland',
        description: 'N/A',
        lat: 55.284,
        lon: -3.622,
    },
    {
        title: 'Clennoch',
        district: 'Galloway',
        region: 'Southern Scotland',
        description: 'N/A',
        lat: 55.276,
        lon: -4.201,
    },
    {
        title: 'Dryfehead',
        district: 'Dumfriesshire',
        region: 'Southern Scotland',
        description: 'N/A',
        lat: 55.286,
        lon: -3.308,
    },
    {
        title: 'Gameshope',
        district: 'Dumfriesshire',
        region: 'Southern Scotland',
        description: 'N/A',
        lat: 55.453,
        lon: -3.371,
    },
    {
        title: 'Greensykes',
        district: 'Dumfriesshire',
        region: 'Southern Scotland',
        description: 'N/A',
        lat: 55.290,
        lon: -3.084,
    },
    {
        title: 'Kettleton Byre',
        district: 'Lowther Hills',
        region: 'Southern Scotland',
        description: 'N/A',
        lat: 55.301,
        lon: -3.716,
    },
    {
        title: `Leysburnfoot (Will's Bothy)`,
        district: 'Liddesdale',
        region: 'Southern Scotland',
        description: 'N/A',
        lat: 55.272,
        lon: -2.732,
    },
    {
        title: 'Over Phawhope',
        district: 'Dumfriesshire',
        region: 'Southern Scotland',
        description: 'N/A',
        lat: 55.361,
        lon: -3.293,
    },
    {
        title: 'Tunskeen',
        district: 'Galloway',
        region: 'Southern Scotland',
        description: 'N/A',
        lat: 55.184,
        lon: -4.476,
    },
    {
        title: 'White Laggan',
        district: 'Galloway',
        region: 'Southern Scotland',
        description: 'N/A',
        lat: 55.068,
        lon: -4.403,
    },
]